### ISSUE TITLE
Поправить автоматическое определение папки с конфигом

### ISSUE THREAD

**Issue by MageNuada** [CADproject/Common#3]
Создать автоматическое определение папки с конфигом на основе местоположения запускаемого скрипта.
![image](https://user-images.githubusercontent.com/22857920/41411823-caacd16c-6fe6-11e8-8f79-60e4079e9673.png)
![image](https://user-images.githubusercontent.com/22857920/41411826-cfea990c-6fe6-11e8-8f2f-195b1d6dda81.png)

**Comment by AlexeyKalinichenko** [comment]
Ну сейчас предполагается, что конфиг лежит в одной папке со скриптом.
А какой у тебя указан путь к конфигу в скрипте (`configPath`) ?

**Comment by MageNuada** [comment]
А, упустил этот момент.
